### ISSUE TITLE
Fails to install on Debian 11 using Ubuntu 21.10 repo (update docs)

### ISSUE THREAD

**Issue by boudiccas** [vkbo/novelWriter#956]
```
sudo apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  novelwriter
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/1,479 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
apt-listchanges warning: Unknown configuration file option: allow-insecure
dpkg-deb: error: archive '/var/cache/apt/archives/novelwriter_1.5.5~ubuntu21.10.0_all.deb' uses unknown compression for member 'control.tar.zst', giving up
Traceback (most recent call last):
  File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
    output = subprocess.check_output(command)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/cache/apt/archives/novelwriter_1.5.5~ubuntu21.10.0_all.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 323, in <module>
    main(config)
  File "/usr/bin/apt-listchanges", line 104, in main
    pkg = DebianFiles.Package(deb)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 358, in __init__
    parser.readdeb(self.path)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 127, in readdeb
    raise RuntimeError(_("Error processing '%(what)s': %(errmsg)s") %
RuntimeError: Error processing '/var/cache/apt/archives/novelwriter_1.5.5~ubuntu21.10.0_all.deb': Command '['dpkg-deb', '-f', '/var/cache/apt/archives/novelwriter_1.5.5~ubuntu21.10.0_all.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
dpkg-deb: error: archive '/var/cache/apt/archives/novelwriter_1.5.5~ubuntu21.10.0_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/novelwriter_1.5.5~ubuntu21.10.0_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/novelwriter_1.5.5~ubuntu21.10.0_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by vkbo** [comment]
Hmm, I'm running Debian 11, and have novelWriter installed via Launchpad. It worked when I released it, and a reinstall ran just fine now. Either there is a difference in configuration, or there was an issue with the service when you ran the install.

I'm not an expert on dpkg, but a quick search reveals similar big reports. Could you try running:
```
sudo apt install --fix-broken
```

**Comment by vkbo** [comment]
Disregard that. I now figured out the issue. You are using the Launchpad repo for Ubuntu 21.10. You should be using the one for Ubuntu 20.04 instead. 21.10 uses a different compression which Debian doesn't support.

I just switched to 21.10 locally and got the same error.

**Comment by vkbo** [comment]
Don't close this. I'm keeping the ticket open to update the documentation.
